import { randomUUID } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import {
  CODEX_ASSISTANT_PROTOCOL_VERSION,
  type ThemeSnapshot,
} from "../../src/contracts";
import { CodexAssistantService } from "../../src/main/assistant/assistant-service";
import { ThemeService } from "../../src/main/app/theme-service";
import { LocalThemeStore } from "../../src/main/infra/local-store";
import { createManagedRoot } from "../fixtures/managed-root";
import { highContrastPalette } from "./palette-validator.test";

const cleanup: Array<() => Promise<void>> = [];

afterEach(async () => {
  await Promise.all(cleanup.splice(0).map((operation) => operation()));
});

describe("Codex assistant service", () => {
  it("creates and updates derived drafts without overwriting saved themes", async () => {
    const managed = await createManagedRoot();
    cleanup.push(managed.cleanup);
    const store = new LocalThemeStore(managed.root);
    await store.init();
    const snapshot = (): ThemeSnapshot =>
      store.snapshot(sessionSnapshot(), updateSnapshot());
    const themes = new ThemeService(store, () => undefined, snapshot);
    const assistant = new CodexAssistantService({
      appVersion: "1.3.12",
      snapshot,
      getTheme: (libraryId) => themes.get(libraryId),
      createDraft: (name) => themes.createDraft(name),
      createDraftFrom: (sourceLibraryId, name) =>
        themes.createDraftFrom(sourceLibraryId, name),
      patchDraft: (libraryId, expectedRevision, patch) =>
        themes.patch(libraryId, expectedRevision, patch),
      selectTheme: (libraryId, expectedRevision) =>
        themes.select(libraryId, expectedRevision),
    });
    const source = store.listRecords()[0];

    const created = await assistant.handle({
      v: CODEX_ASSISTANT_PROTOCOL_VERSION,
      id: randomUUID(),
      method: "create_theme_draft",
      params: { name: "Agent draft", sourceLibraryId: source.libraryId },
    });
    expect(created.ok).toBe(true);
    const draft = (created as { ok: true; data: Record<string, unknown> }).data;
    expect(draft).toMatchObject({ name: "Agent draft", status: "draft" });

    const unreadable = highContrastPalette();
    unreadable.accentText = unreadable.accent;
    const rejectedPalette = await assistant.handle({
      v: CODEX_ASSISTANT_PROTOCOL_VERSION,
      id: randomUUID(),
      method: "update_theme_draft",
      params: {
        libraryId: String(draft.libraryId),
        expectedRevision: Number(draft.revision),
        colors: unreadable,
      },
    });
    expect(rejectedPalette).toMatchObject({
      ok: false,
      error: { code: "PALETTE_CONTRAST_FAILED" },
    });
    expect(store.get(String(draft.libraryId))?.revision).toBe(draft.revision);

    const updated = await assistant.handle({
      v: CODEX_ASSISTANT_PROTOCOL_VERSION,
      id: randomUUID(),
      method: "update_theme_draft",
      params: {
        libraryId: String(draft.libraryId),
        expectedRevision: Number(draft.revision),
        colors: highContrastPalette(),
        appearance: "dark",
        description: "Generated by Codex",
      },
    });
    expect(updated.ok).toBe(true);
    expect(
      store.getDetail(String(draft.libraryId), "app://theme-asset"),
    ).toMatchObject({
      description: "Generated by Codex",
      appearance: "dark",
      colors: { accent: "#f5c451" },
    });

    const stale = await assistant.handle({
      v: CODEX_ASSISTANT_PROTOCOL_VERSION,
      id: randomUUID(),
      method: "update_theme_draft",
      params: {
        libraryId: String(draft.libraryId),
        expectedRevision: Number(draft.revision),
        colors: highContrastPalette(),
      },
    });
    expect(stale).toMatchObject({
      ok: false,
      error: { code: "STALE_REVISION" },
    });

    const overwrite = await assistant.handle({
      v: CODEX_ASSISTANT_PROTOCOL_VERSION,
      id: randomUUID(),
      method: "update_theme_draft",
      params: {
        libraryId: source.libraryId,
        expectedRevision: source.revision,
        colors: highContrastPalette(),
      },
    });
    expect(overwrite).toMatchObject({
      ok: false,
      error: { code: "READY_THEME_IMMUTABLE" },
    });
    expect(store.get(source.libraryId)?.status).toBe("ready");
  });

  it("only selects complete saved themes", async () => {
    const managed = await createManagedRoot();
    cleanup.push(managed.cleanup);
    const store = new LocalThemeStore(managed.root);
    await store.init();
    const snapshot = (): ThemeSnapshot =>
      store.snapshot(sessionSnapshot(), updateSnapshot());
    const themes = new ThemeService(store, () => undefined, snapshot);
    const assistant = new CodexAssistantService({
      appVersion: "1.3.12",
      snapshot,
      getTheme: (libraryId) => themes.get(libraryId),
      createDraft: (name) => themes.createDraft(name),
      createDraftFrom: (sourceLibraryId, name) =>
        themes.createDraftFrom(sourceLibraryId, name),
      patchDraft: (libraryId, expectedRevision, patch) =>
        themes.patch(libraryId, expectedRevision, patch),
      selectTheme: (libraryId, expectedRevision) =>
        themes.select(libraryId, expectedRevision),
    });
    const draft = await store.createDraft("Not ready");
    const rejected = await assistant.handle({
      v: CODEX_ASSISTANT_PROTOCOL_VERSION,
      id: randomUUID(),
      method: "select_theme",
      params: { libraryId: draft.libraryId, expectedRevision: draft.revision },
    });
    expect(rejected).toMatchObject({
      ok: false,
      error: { code: "INCOMPLETE_THEME" },
    });

    const ready = store
      .listRecords()
      .find((theme) => theme.status === "ready")!;
    const selected = await assistant.handle({
      v: CODEX_ASSISTANT_PROTOCOL_VERSION,
      id: randomUUID(),
      method: "select_theme",
      params: { libraryId: ready.libraryId, expectedRevision: ready.revision },
    });
    expect(selected).toMatchObject({
      ok: true,
      data: { selectedLibraryId: ready.libraryId },
    });
  });
});

function sessionSnapshot(): ThemeSnapshot["session"] {
  return {
    state: "NO_SESSION",
    messageKey: "session.none",
    canEnd: false,
    launchedByTool: false,
  };
}

function updateSnapshot(): ThemeSnapshot["update"] {
  return {
    configured: false,
    status: "unsupported",
    currentVersion: "1.3.12",
  };
}
