import type {
  ThemeAppearance,
  ThemeColors,
  ThemeDetail,
  ThemeStyleConfig,
} from "../../../contracts";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  appearance: Exclude<ThemeAppearance, "auto">;
  colors: ThemeColors;
  styleConfig: Omit<ThemeStyleConfig, "sendIcon" | "sendIconDataUrl">;
}

const enabledRecipes: ThemeStyleConfig["recipes"] = {
  sidebar: true,
  composer: true,
  message: true,
  dialog: true,
};

export const THEME_PRESETS = [
  {
    id: "paper-light",
    name: "纸张白",
    description: "温暖、克制的明亮工作台",
    appearance: "light",
    colors: {
      background: "#f6f3ec",
      panel: "#ebe7dd",
      sidebarText: "#42464d",
      threadTabBackground: "#ebe7dd",
      threadTabText: "#72777f",
      homeTitleText: "#25262a",
      homeCardBackground: "#ebe7dd",
      homeCardText: "#25262a",
      panelAlt: "#ffffff",
      assistantPanel: "#ffffff",
      assistantMessageText: "#25262a",
      changeCardBackground: "rgba(255, 255, 255, 0.9)",
      changeCardText: "#25262a",
      activityBackground: "#ebe7dd",
      activityText: "#25262a",
      activityMuted: "#72777f",
      userMessageText: "#25262a",
      topBarBackground: "rgba(0, 0, 0, 0)",
      topBarText: "#72777f",
      accent: "#1f6feb",
      accentAlt: "#3b82f6",
      secondary: "#7d8795",
      highlight: "#e7f0ff",
      text: "#25262a",
      muted: "#72777f",
      line: "#d6d2c8",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 8,
      radius: 12,
      borderWidth: 1,
      shadow: "soft",
    },
  },
  {
    id: "graphite",
    name: "石墨灰",
    description: "低干扰的中性深色界面",
    appearance: "dark",
    colors: {
      background: "#171918",
      panel: "#202321",
      sidebarText: "#d7ddd7",
      threadTabBackground: "#202321",
      threadTabText: "#9aa19b",
      homeTitleText: "#f4f6f3",
      homeCardBackground: "#202321",
      homeCardText: "#f4f6f3",
      panelAlt: "#292d2a",
      assistantPanel: "#292d2a",
      assistantMessageText: "#f4f6f3",
      changeCardBackground: "rgba(41, 45, 42, 0.9)",
      changeCardText: "#f4f6f3",
      activityBackground: "#202321",
      activityText: "#f4f6f3",
      activityMuted: "#9aa19b",
      userMessageText: "#f4f6f3",
      topBarBackground: "rgba(0, 0, 0, 0)",
      topBarText: "#9aa19b",
      accent: "#eef0ed",
      accentAlt: "#b8beb8",
      secondary: "#717973",
      highlight: "#353a36",
      text: "#f4f6f3",
      muted: "#9aa19b",
      line: "#3a403b",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 6,
      radius: 10,
      borderWidth: 1,
      shadow: "none",
    },
  },
  {
    id: "midnight-copper",
    name: "午夜铜",
    description: "深蓝底色与温暖铜金强调",
    appearance: "dark",
    colors: {
      background: "#101621",
      panel: "#151e2d",
      sidebarText: "#dce6f6",
      threadTabBackground: "#151e2d",
      threadTabText: "#9aa8ba",
      homeTitleText: "#f4eee6",
      homeCardBackground: "#151e2d",
      homeCardText: "#f4eee6",
      panelAlt: "#1d293a",
      assistantPanel: "#1d293a",
      assistantMessageText: "#f4eee6",
      changeCardBackground: "rgba(29, 41, 58, 0.9)",
      changeCardText: "#f4eee6",
      activityBackground: "#151e2d",
      activityText: "#f4eee6",
      activityMuted: "#9aa8ba",
      userMessageText: "#f4eee6",
      topBarBackground: "rgba(0, 0, 0, 0)",
      topBarText: "#9aa8ba",
      accent: "#f2a65a",
      accentAlt: "#d9823b",
      secondary: "#50627a",
      highlight: "#2f4057",
      text: "#f4eee6",
      muted: "#9aa8ba",
      line: "#31415a",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 18,
      radius: 14,
      borderWidth: 1,
      shadow: "soft",
    },
  },
  {
    id: "aurora-cyan",
    name: "极光青",
    description: "冷冽青蓝与通透磨砂表面",
    appearance: "dark",
    colors: {
      background: "#071b22",
      panel: "#0c2730",
      sidebarText: "#d5f7f4",
      threadTabBackground: "#0c2730",
      threadTabText: "#84aeb2",
      homeTitleText: "#e6fffb",
      homeCardBackground: "#0c2730",
      homeCardText: "#e6fffb",
      panelAlt: "#123640",
      assistantPanel: "#123640",
      assistantMessageText: "#e6fffb",
      changeCardBackground: "rgba(18, 54, 64, 0.88)",
      changeCardText: "#e6fffb",
      activityBackground: "#0c2730",
      activityText: "#e6fffb",
      activityMuted: "#84aeb2",
      userMessageText: "#e6fffb",
      topBarBackground: "rgba(0, 0, 0, 0)",
      topBarText: "#84aeb2",
      accent: "#5eead4",
      accentAlt: "#38bdf8",
      secondary: "#3c6770",
      highlight: "#174d58",
      text: "#e6fffb",
      muted: "#84aeb2",
      line: "#25515a",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 22,
      radius: 16,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "sakura-mist",
    name: "樱雾粉",
    description: "柔和粉白与清晰深色文字",
    appearance: "light",
    colors: {
      background: "#fff7f8",
      panel: "#f8e8ec",
      sidebarText: "#513841",
      threadTabBackground: "#f8e8ec",
      threadTabText: "#846a73",
      homeTitleText: "#412b33",
      homeCardBackground: "#f8e8ec",
      homeCardText: "#412b33",
      panelAlt: "#fffdfd",
      assistantPanel: "#fffdfd",
      assistantMessageText: "#412b33",
      changeCardBackground: "rgba(255, 253, 253, 0.9)",
      changeCardText: "#412b33",
      activityBackground: "#f8e8ec",
      activityText: "#412b33",
      activityMuted: "#846a73",
      userMessageText: "#412b33",
      topBarBackground: "rgba(0, 0, 0, 0)",
      topBarText: "#846a73",
      accent: "#d85b7d",
      accentAlt: "#a53e63",
      secondary: "#a98b94",
      highlight: "#f8dbe4",
      text: "#412b33",
      muted: "#846a73",
      line: "#ead0d7",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 12,
      radius: 18,
      borderWidth: 1,
      shadow: "soft",
    },
  },
  {
    id: "terminal-green",
    name: "终端绿",
    description: "硬朗、紧凑的复古终端气质",
    appearance: "dark",
    colors: {
      background: "#07100a",
      panel: "#0b1a10",
      sidebarText: "#b9f7ca",
      threadTabBackground: "#0b1a10",
      threadTabText: "#78a785",
      homeTitleText: "#d8ffe3",
      homeCardBackground: "#0b1a10",
      homeCardText: "#d8ffe3",
      panelAlt: "#102318",
      assistantPanel: "#102318",
      assistantMessageText: "#d8ffe3",
      changeCardBackground: "rgba(16, 35, 24, 0.92)",
      changeCardText: "#d8ffe3",
      activityBackground: "#0b1a10",
      activityText: "#d8ffe3",
      activityMuted: "#78a785",
      userMessageText: "#d8ffe3",
      topBarBackground: "rgba(0, 0, 0, 0)",
      topBarText: "#78a785",
      accent: "#71f79f",
      accentAlt: "#2fd56d",
      secondary: "#3d6b4d",
      highlight: "#153c24",
      text: "#d8ffe3",
      muted: "#78a785",
      line: "#214d31",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 0,
      radius: 6,
      borderWidth: 1,
      shadow: "none",
    },
  },
] as const satisfies ReadonlyArray<ThemePreset>;

export function applyThemePreset(
  draft: ThemeDetail,
  preset: ThemePreset,
): ThemeDetail {
  return {
    ...draft,
    appearance: preset.appearance,
    colors: { ...preset.colors },
    styleConfig: {
      ...draft.styleConfig,
      ...preset.styleConfig,
      recipes: { ...preset.styleConfig.recipes },
    },
  };
}

export function isThemePresetActive(
  draft: ThemeDetail,
  preset: ThemePreset,
): boolean {
  return (
    draft.appearance === preset.appearance &&
    equalRecord(draft.colors, preset.colors) &&
    draft.styleConfig.mode === preset.styleConfig.mode &&
    draft.styleConfig.blur === preset.styleConfig.blur &&
    draft.styleConfig.radius === preset.styleConfig.radius &&
    draft.styleConfig.borderWidth === preset.styleConfig.borderWidth &&
    draft.styleConfig.shadow === preset.styleConfig.shadow &&
    equalRecord(draft.styleConfig.recipes, preset.styleConfig.recipes)
  );
}

function equalRecord<T extends object>(left: T, right: T) {
  return (Object.keys(left) as Array<keyof T>).every(
    (key) => left[key] === right[key],
  );
}
