import {
  createDefaultThemeHomeCards,
  type ThemeAppearance,
  type ThemeColors,
  type ThemeDetail,
  type ThemeStyleConfig,
} from "../../../contracts";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  appearance: Exclude<ThemeAppearance, "auto">;
  colors: ThemeColors;
  styleConfig: Omit<ThemeStyleConfig, "sendIcon" | "sendIconDataUrl">;
}

const enabledRecipes: ThemeStyleConfig["recipes"] = {
  sidebar: true,
  composer: true,
  message: true,
  dialog: true,
};

interface LuxuryPalette {
  background: string;
  panel: string;
  chrome: string;
  card: string;
  input: string;
  assistant: string;
  activity: string;
  foreground: string;
  subtle: string;
  accent: string;
  accentText: string;
  focus: string;
  selection: string;
  selectionText: string;
  line: string;
}

function createLuxuryColors(palette: LuxuryPalette): ThemeColors {
  return {
    background: palette.background,
    panel: palette.panel,
    sidebarText: palette.foreground,
    threadTabBackground: palette.chrome,
    threadTabText: palette.subtle,
    homeTitleText: palette.foreground,
    homeCardBackground: palette.card,
    homeCardText: palette.foreground,
    panelAlt: palette.input,
    composerText: palette.foreground,
    assistantPanel: palette.assistant,
    assistantMessageText: palette.foreground,
    userMessageText: palette.foreground,
    changeCardBackground: palette.input,
    changeCardText: palette.foreground,
    activityBackground: palette.activity,
    activityText: palette.foreground,
    activityMuted: palette.subtle,
    topBarBackground: palette.chrome,
    topBarText: palette.subtle,
    accent: palette.accent,
    accentText: palette.accentText,
    accentAlt: palette.focus,
    secondary: palette.subtle,
    highlight: palette.selection,
    selectionText: palette.selectionText,
    text: palette.foreground,
    muted: palette.subtle,
    line: palette.line,
  };
}

export const THEME_PRESETS = [
  {
    id: "emerald-bronze",
    name: "墨绿古铜",
    description: "深墨绿丝绒、古铜金属与暖象牙文字",
    appearance: "dark",
    colors: {
      background: "rgba(9, 45, 36, 0.2)",
      panel: "rgba(12, 55, 43, 0.2)",
      sidebarText: "#f3ead7",
      threadTabBackground: "rgba(8, 38, 31, 0.88)",
      threadTabText: "#d9c7a2",
      homeTitleText: "#fff4df",
      homeCardBackground: "rgba(10, 43, 35, 0.86)",
      homeCardText: "#f6ecd8",
      panelAlt: "rgba(7, 35, 29, 0.92)",
      composerText: "#fff4df",
      assistantPanel: "rgba(12, 48, 39, 0.88)",
      assistantMessageText: "#f3ead7",
      userMessageText: "#fff4df",
      changeCardBackground: "rgba(7, 34, 28, 0.92)",
      changeCardText: "#f3ead7",
      activityBackground: "rgba(13, 51, 41, 0.8)",
      activityText: "#eadfc8",
      activityMuted: "#b9aa8e",
      topBarBackground: "rgba(6, 31, 26, 0.62)",
      topBarText: "#d9c7a2",
      accent: "#b8894f",
      accentText: "#1d1207",
      accentAlt: "#d4ad73",
      secondary: "#b8a98d",
      highlight: "#d4ad73",
      selectionText: "#1b2c25",
      text: "#f3ead7",
      muted: "#ad9f87",
      line: "rgba(200, 159, 99, 0.2)",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 18,
      radius: 14,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "navy-silver",
    name: "藏蓝银辉",
    description: "深藏蓝玻璃、拉丝银与冷白高光",
    appearance: "dark",
    colors: {
      background: "rgba(10, 25, 48, 0.2)",
      panel: "rgba(14, 34, 62, 0.2)",
      sidebarText: "#f1f5f9",
      threadTabBackground: "rgba(12, 29, 52, 0.88)",
      threadTabText: "#cbd5df",
      homeTitleText: "#f8fbff",
      homeCardBackground: "rgba(15, 36, 64, 0.86)",
      homeCardText: "#f2f6fa",
      panelAlt: "rgba(10, 27, 50, 0.92)",
      composerText: "#f8fbff",
      assistantPanel: "rgba(16, 38, 67, 0.88)",
      assistantMessageText: "#f1f5f9",
      userMessageText: "#f8fbff",
      changeCardBackground: "rgba(10, 27, 50, 0.92)",
      changeCardText: "#f1f5f9",
      activityBackground: "rgba(17, 40, 70, 0.8)",
      activityText: "#e4ebf2",
      activityMuted: "#a9b6c4",
      topBarBackground: "rgba(8, 23, 43, 0.62)",
      topBarText: "#cbd5df",
      accent: "#c9d2dc",
      accentText: "#11243c",
      accentAlt: "#6da8d6",
      secondary: "#aab8c6",
      highlight: "#d7e0e9",
      selectionText: "#10223a",
      text: "#f1f5f9",
      muted: "#9fadb9",
      line: "rgba(201, 210, 220, 0.2)",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 22,
      radius: 12,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "burgundy-champagne",
    name: "酒红香槟",
    description: "酒红漆面、香槟金与丝绒奶油白",
    appearance: "dark",
    colors: {
      background: "rgba(74, 12, 30, 0.2)",
      panel: "rgba(91, 18, 40, 0.2)",
      sidebarText: "#fff0df",
      threadTabBackground: "rgba(72, 11, 29, 0.88)",
      threadTabText: "#e8cba2",
      homeTitleText: "#fff4e7",
      homeCardBackground: "rgba(83, 15, 36, 0.86)",
      homeCardText: "#fff1e2",
      panelAlt: "rgba(68, 10, 27, 0.92)",
      composerText: "#fff4e7",
      assistantPanel: "rgba(88, 16, 38, 0.88)",
      assistantMessageText: "#fff0df",
      userMessageText: "#fff4e7",
      changeCardBackground: "rgba(67, 10, 27, 0.92)",
      changeCardText: "#fff0df",
      activityBackground: "rgba(91, 18, 40, 0.8)",
      activityText: "#f5dfc4",
      activityMuted: "#c9a68b",
      topBarBackground: "rgba(60, 8, 24, 0.62)",
      topBarText: "#e8cba2",
      accent: "#e3c28f",
      accentText: "#47101f",
      accentAlt: "#c75d78",
      secondary: "#c8aa91",
      highlight: "#e3c28f",
      selectionText: "#45101f",
      text: "#fff0df",
      muted: "#bea087",
      line: "rgba(227, 194, 143, 0.2)",
    },
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 18,
      radius: 16,
      borderWidth: 1,
      shadow: "soft",
    },
  },
  {
    id: "amethyst-pearl",
    name: "紫晶珍珠",
    description: "深紫天鹅绒、珍珠白与紫晶金属高光",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(44, 25, 68, 0.2)",
      panel: "rgba(59, 36, 86, 0.2)",
      chrome: "rgba(43, 25, 66, 0.88)",
      card: "rgba(57, 35, 84, 0.86)",
      input: "rgba(40, 23, 61, 0.92)",
      assistant: "rgba(61, 39, 88, 0.88)",
      activity: "rgba(64, 41, 92, 0.8)",
      foreground: "#f7f2fb",
      subtle: "#c7b9d3",
      accent: "#ddd4e9",
      accentText: "#2f1b47",
      focus: "#a985c5",
      selection: "#e4dced",
      selectionText: "#301b48",
      line: "rgba(211, 195, 225, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 22,
      radius: 18,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "ivory-rose-gold",
    name: "奶油玫瑰金",
    description: "奶油白皮革、玫瑰金与柔和可可文字",
    appearance: "light",
    colors: createLuxuryColors({
      background: "rgba(246, 239, 227, 0.2)",
      panel: "rgba(239, 225, 217, 0.2)",
      chrome: "rgba(255, 249, 243, 0.9)",
      card: "rgba(255, 250, 244, 0.9)",
      input: "rgba(255, 252, 247, 0.95)",
      assistant: "rgba(250, 239, 232, 0.92)",
      activity: "rgba(240, 225, 216, 0.86)",
      foreground: "#47343a",
      subtle: "#795f67",
      accent: "#b96f7d",
      accentText: "#251216",
      focus: "#d5a38f",
      selection: "#5f3d48",
      selectionText: "#fff9f4",
      line: "rgba(113, 78, 87, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 24,
      radius: 20,
      borderWidth: 1,
      shadow: "soft",
    },
  },
  {
    id: "charcoal-sapphire",
    name: "炭灰蓝宝石",
    description: "炭灰金属、宝石蓝与纯白冷光",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(30, 32, 36, 0.2)",
      panel: "rgba(41, 44, 50, 0.2)",
      chrome: "rgba(27, 29, 34, 0.9)",
      card: "rgba(37, 40, 47, 0.88)",
      input: "rgba(25, 27, 32, 0.94)",
      assistant: "rgba(42, 45, 52, 0.9)",
      activity: "rgba(45, 48, 56, 0.82)",
      foreground: "#f2f5fa",
      subtle: "#aab4c2",
      accent: "#286ac7",
      accentText: "#ffffff",
      focus: "#74aaf3",
      selection: "#bfd7ff",
      selectionText: "#15233b",
      line: "rgba(104, 155, 224, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 16,
      radius: 10,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "obsidian-gold",
    name: "黑曜鎏金",
    description: "黑曜石漆面、鎏金细节与暖象牙白",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(5, 6, 8, 0.2)",
      panel: "rgba(15, 16, 18, 0.2)",
      chrome: "rgba(10, 11, 13, 0.9)",
      card: "rgba(18, 19, 22, 0.88)",
      input: "rgba(8, 9, 11, 0.94)",
      assistant: "rgba(20, 21, 24, 0.9)",
      activity: "rgba(23, 24, 28, 0.82)",
      foreground: "#fff3d4",
      subtle: "#c5b58f",
      accent: "#d9a441",
      accentText: "#1d1404",
      focus: "#f0ca72",
      selection: "#e4bc63",
      selectionText: "#1d1404",
      line: "rgba(217, 164, 65, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 10,
      radius: 8,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "jade-porcelain",
    name: "青玉瓷白",
    description: "青玉釉色、瓷白表面与茶铜点缀",
    appearance: "light",
    colors: createLuxuryColors({
      background: "rgba(221, 239, 230, 0.2)",
      panel: "rgba(232, 244, 237, 0.2)",
      chrome: "rgba(249, 253, 250, 0.9)",
      card: "rgba(250, 254, 251, 0.9)",
      input: "rgba(252, 255, 253, 0.95)",
      assistant: "rgba(241, 249, 244, 0.92)",
      activity: "rgba(225, 240, 231, 0.86)",
      foreground: "#173e34",
      subtle: "#557369",
      accent: "#8b5c34",
      accentText: "#fffaf2",
      focus: "#2a7964",
      selection: "#1f5b4d",
      selectionText: "#f8fffb",
      line: "rgba(23, 62, 52, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 18,
      radius: 16,
      borderWidth: 1,
      shadow: "soft",
    },
  },
  {
    id: "deep-sea-platinum",
    name: "深海铂金",
    description: "深海青玻璃、铂金冷光与克制蓝绿焦点",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(4, 42, 50, 0.2)",
      panel: "rgba(6, 53, 62, 0.2)",
      chrome: "rgba(4, 38, 46, 0.9)",
      card: "rgba(7, 49, 58, 0.88)",
      input: "rgba(3, 35, 42, 0.94)",
      assistant: "rgba(8, 54, 63, 0.9)",
      activity: "rgba(9, 58, 67, 0.82)",
      foreground: "#edf7f7",
      subtle: "#a9c1c3",
      accent: "#cdd8d9",
      accentText: "#0a3035",
      focus: "#39a6a6",
      selection: "#dce7e7",
      selectionText: "#0c3036",
      line: "rgba(192, 217, 218, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 20,
      radius: 14,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "ruby-black-titanium",
    name: "红宝石黑钛",
    description: "红宝石漆面、黑钛金属与冷银边界",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(56, 6, 15, 0.2)",
      panel: "rgba(71, 9, 20, 0.2)",
      chrome: "rgba(49, 5, 13, 0.9)",
      card: "rgba(65, 8, 18, 0.88)",
      input: "rgba(45, 4, 11, 0.94)",
      assistant: "rgba(73, 10, 21, 0.9)",
      activity: "rgba(77, 11, 23, 0.82)",
      foreground: "#fff1f3",
      subtle: "#c7a7ad",
      accent: "#c92d57",
      accentText: "#fff7f8",
      focus: "#9da3aa",
      selection: "#f2d7dc",
      selectionText: "#43101a",
      line: "rgba(202, 209, 216, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 16,
      radius: 12,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "midnight-copper-blue",
    name: "午夜铜蓝",
    description: "午夜蓝丝绒、氧化铜与暖白文字",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(10, 22, 38, 0.2)",
      panel: "rgba(15, 31, 50, 0.2)",
      chrome: "rgba(9, 23, 39, 0.9)",
      card: "rgba(14, 30, 49, 0.88)",
      input: "rgba(7, 20, 34, 0.94)",
      assistant: "rgba(17, 34, 54, 0.9)",
      activity: "rgba(19, 38, 60, 0.82)",
      foreground: "#f7efe8",
      subtle: "#b7a99e",
      accent: "#c47b4b",
      accentText: "#211006",
      focus: "#66a7a0",
      selection: "#e0ad87",
      selectionText: "#2b160b",
      line: "rgba(196, 123, 75, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 18,
      radius: 14,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "espresso-brass",
    name: "浓缩黄铜",
    description: "浓缩咖啡丝绒、黄铜与奶泡白",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(42, 28, 23, 0.2)",
      panel: "rgba(55, 36, 29, 0.2)",
      chrome: "rgba(37, 24, 20, 0.9)",
      card: "rgba(50, 32, 26, 0.88)",
      input: "rgba(33, 21, 17, 0.94)",
      assistant: "rgba(57, 38, 30, 0.9)",
      activity: "rgba(61, 41, 33, 0.82)",
      foreground: "#fff3df",
      subtle: "#c7ad91",
      accent: "#c89b52",
      accentText: "#291a08",
      focus: "#8e5f43",
      selection: "#dfbd83",
      selectionText: "#301e0d",
      line: "rgba(200, 155, 82, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 16,
      radius: 12,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "slate-ice",
    name: "岩灰冰晶",
    description: "岩板灰、冰晶蓝与雾白玻璃",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(48, 57, 66, 0.2)",
      panel: "rgba(59, 70, 80, 0.2)",
      chrome: "rgba(43, 51, 60, 0.9)",
      card: "rgba(55, 65, 75, 0.88)",
      input: "rgba(39, 47, 55, 0.94)",
      assistant: "rgba(61, 72, 83, 0.9)",
      activity: "rgba(65, 77, 89, 0.82)",
      foreground: "#edf8ff",
      subtle: "#b5c7d2",
      accent: "#91d6ee",
      accentText: "#13303c",
      focus: "#c2e8f5",
      selection: "#d5eef7",
      selectionText: "#213440",
      line: "rgba(145, 214, 238, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 22,
      radius: 16,
      borderWidth: 1,
      shadow: "soft",
    },
  },
  {
    id: "peacock-matte-gold",
    name: "孔雀哑金",
    description: "孔雀蓝绿、哑光金与象牙白高光",
    appearance: "dark",
    colors: createLuxuryColors({
      background: "rgba(3, 49, 60, 0.2)",
      panel: "rgba(3, 62, 73, 0.2)",
      chrome: "rgba(2, 44, 54, 0.9)",
      card: "rgba(4, 57, 68, 0.88)",
      input: "rgba(2, 40, 49, 0.94)",
      assistant: "rgba(5, 64, 75, 0.9)",
      activity: "rgba(6, 68, 80, 0.82)",
      foreground: "#fff4dd",
      subtle: "#c7ba9c",
      accent: "#c7a861",
      accentText: "#15302f",
      focus: "#2bb1ae",
      selection: "#d9be79",
      selectionText: "#15302f",
      line: "rgba(199, 168, 97, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 20,
      radius: 16,
      borderWidth: 1,
      shadow: "strong",
    },
  },
  {
    id: "pearl-graphite",
    name: "珍珠石墨",
    description: "珍珠灰、抛光石墨与细腻银白层次",
    appearance: "light",
    colors: createLuxuryColors({
      background: "rgba(230, 231, 234, 0.2)",
      panel: "rgba(216, 218, 222, 0.2)",
      chrome: "rgba(250, 250, 251, 0.92)",
      card: "rgba(252, 252, 253, 0.92)",
      input: "rgba(254, 254, 255, 0.96)",
      assistant: "rgba(244, 245, 247, 0.92)",
      activity: "rgba(222, 224, 228, 0.88)",
      foreground: "#292c31",
      subtle: "#60666f",
      accent: "#4e5865",
      accentText: "#ffffff",
      focus: "#9da5ae",
      selection: "#353b43",
      selectionText: "#ffffff",
      line: "rgba(41, 44, 49, 0.2)",
    }),
    styleConfig: {
      mode: "configured",
      recipes: enabledRecipes,
      blur: 18,
      radius: 14,
      borderWidth: 1,
      shadow: "soft",
    },
  },
] as const satisfies ReadonlyArray<ThemePreset>;

export function applyThemePreset(
  draft: ThemeDetail,
  preset: ThemePreset,
): ThemeDetail {
  return {
    ...draft,
    appearance: preset.appearance,
    colors: { ...preset.colors },
    homeCards: createDefaultThemeHomeCards(preset.colors.homeCardBackground),
    styleConfig: {
      ...draft.styleConfig,
      ...preset.styleConfig,
      recipes: { ...preset.styleConfig.recipes },
    },
  };
}

export function isThemePresetActive(
  draft: ThemeDetail,
  preset: ThemePreset,
): boolean {
  return (
    draft.appearance === preset.appearance &&
    equalRecord(draft.colors, preset.colors) &&
    draft.homeCards.every(
      (card) =>
        card.mode === "color" &&
        card.color === preset.colors.homeCardBackground &&
        card.imageDataUrl === undefined,
    ) &&
    draft.styleConfig.mode === preset.styleConfig.mode &&
    draft.styleConfig.blur === preset.styleConfig.blur &&
    draft.styleConfig.radius === preset.styleConfig.radius &&
    draft.styleConfig.borderWidth === preset.styleConfig.borderWidth &&
    draft.styleConfig.shadow === preset.styleConfig.shadow &&
    equalRecord(draft.styleConfig.recipes, preset.styleConfig.recipes)
  );
}

function equalRecord<T extends object>(left: T, right: T) {
  return (Object.keys(left) as Array<keyof T>).every(
    (key) => left[key] === right[key],
  );
}
